/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/head.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Head(props) {
  const { nodes, materials } = useGLTF("/head.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials["Material.002"]}
        position={[0.09, 0.53, 0]}
        scale={[0.27, 0.36, 0.28]}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials["Material.012"]}
        position={[0.07, 0.55, -0.33]}
        scale={0.04}
      >
        <mesh
          geometry={nodes.Sphere021.geometry}
          material={materials["Material.012"]}
          position={[-5.87, 0, 3.14]}
        />
        <mesh
          geometry={nodes.Sphere024.geometry}
          material={materials["Material.012"]}
          position={[-5.53, 0, 14.21]}
        />
        <mesh
          geometry={nodes.Sphere001.geometry}
          material={materials["Material.012"]}
          position={[9.09, 0, 8.21]}
        />
        <mesh
          geometry={nodes.Sphere015.geometry}
          material={materials["Material.012"]}
          position={[6.48, 0, 2.27]}
        />
        <mesh
          geometry={nodes.Sphere016.geometry}
          material={materials["Material.012"]}
          position={[6.09, 0, 14.94]}
        />
      </mesh>
      <group position={[-0.01, 1.13, 0]}>
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Glass}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.Glass}
        position={[-0.01, 1.13, 0]}
        scale={1.01}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials.Glass}
        position={[-0.01, 1.13, 0]}
        scale={1.01}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.009"]}
        position={[-0.01, 1.13, 0]}
        scale={1.01}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.009"]}
        position={[-0.01, -0.81, 0]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials["Glass.001"]}
        position={[0, 0.83, 0.62]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials["Glass.001"]}
        position={[0, 0.65, -0.58]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials["Glass.001"]}
        position={[0, 0.76, -0.52]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Sphere006.geometry}
        material={materials["Glass.001"]}
        position={[0, 0.94, -0.63]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Sphere008.geometry}
        material={materials["Glass.001"]}
        position={[0, 0.88, -0.58]}
        scale={0.02}
      />
      <mesh
        geometry={nodes.Sphere009.geometry}
        material={materials["Glass.001"]}
        position={[0, 0.59, 0.51]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Sphere011.geometry}
        material={materials["Glass.001"]}
        position={[0, 2.12, 0.62]}
        scale={0.08}
      />
      <mesh
        geometry={nodes.Sphere012.geometry}
        material={materials["Glass.001"]}
        position={[0, 1.72, 0.69]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.Sphere013.geometry}
        material={materials["Glass.001"]}
        position={[-0.07, 2.16, -0.68]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.Sphere014.geometry}
        material={materials["Glass.001"]}
        position={[0, 1.68, -0.64]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material.013"]}
        position={[0, 0.2, 0]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.003"]}
        position={[-0.85, 0.19, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.14}
      />
      <mesh
        name="EyeLeft001"
        geometry={nodes.EyeLeft001.geometry}
        material={materials["Wolf3D_Eye.001"]}
        morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Avatar"
        geometry={nodes.Wolf3D_Avatar.geometry}
        material={materials["Wolf3D_Avatar.002"]}
        morphTargetDictionary={nodes.Wolf3D_Avatar.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Avatar.morphTargetInfluences}
        position={[0.09, -8.34, -0.01]}
        rotation={[0, -1.57, 0]}
        scale={5.61}
      />
    </group>
  );
}

useGLTF.preload("/head.glb");
