/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/mac.glb -t 
*/

import * as THREE from "three";
import { useEffect, useRef } from "react";
import { useFrame, GroupProps } from "@react-three/fiber";

import { useGLTF, Html } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import useGlobalStore from "@/hooks/useGlobalStore";

import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

import React from "@/public/icons/React";
import SpringBoot from "@/public/icons/SpringBoot";
import Next from "@/public/icons/Next";
import Postgres from "@/public/icons/Postgres";
import Java from "@/public/icons/Java";
import Javascript from "@/public/icons/Javascript";

type GLTFResult = GLTF & {
  nodes: {
    Cube008: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    keyboard: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    touchbar: THREE.Mesh;
  };
  materials: {
    aluminium: THREE.MeshStandardMaterial;
    ["matte.001"]: THREE.MeshStandardMaterial;
    ["screen.001"]: THREE.MeshStandardMaterial;
    keys: THREE.MeshStandardMaterial;
    trackpad: THREE.MeshStandardMaterial;
    touchbar: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Mac(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/mac.glb") as GLTFResult;
  const group = useRef<THREE.Group>(null);
  const previewLink = useGlobalStore((state) => state.previewLink);

  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    if (group.current) {
      group.current.rotation.x = THREE.MathUtils.lerp(
        group.current.rotation.x,
        Math.cos(t / 2) / 20 + 0.25,
        0.1
      );
      group.current.rotation.y = THREE.MathUtils.lerp(
        group.current.rotation.y,
        Math.sin(t / 4) / 20,
        0.1
      );
      group.current.rotation.z = THREE.MathUtils.lerp(
        group.current.rotation.z,
        Math.sin(t / 8) / 20,
        0.1
      );
      group.current.position.y = THREE.MathUtils.lerp(
        group.current.position.y,
        (-2 + Math.sin(t / 2)) / 2,
        0.1
      );
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.002, -0.038, 0.414]} rotation={[0.014, 0, 0]}>
        <group position={[0, 2.965, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Cube008.geometry}
            material={materials.aluminium}
          />
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["matte.001"]}
          />
          <mesh geometry={nodes.Cube008_2.geometry}>
            <Html
              className="htmlScreen"
              distanceFactor={2.5}
              rotation-x={-Math.PI / 2}
              position={[0, 0.039, -0.17]}
              transform
              occlude
            >
              <iframe src={previewLink} />
            </Html>
          </mesh>
        </group>
      </group>
      <mesh
        geometry={nodes.keyboard.geometry}
        material={materials.keys}
        position={[1.793, 0, 3.451]}
      />
      <group position={[0, -0.1, 3.394]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials.aluminium}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials.trackpad}
        />
      </group>
      <mesh
        geometry={nodes.touchbar.geometry}
        material={materials.touchbar}
        position={[0, -0.027, 1.201]}
      />
      <Html
        scale={1}
        rotation={[0, 0, 0]}
        position={[2, 7.2, 0]}
        transform
        occlude
      >
        <div className="bg-[#303030] rounded-full p-2 cursor-pointer  ">
          <Javascript width={25} height={25} />
        </div>
      </Html>
      <Html
        scale={1}
        rotation={[0, 0, 0]}
        position={[-2, 7, 0]}
        transform
        occlude
      >
        <div className="bg-[#303030] rounded-full p-2 cursor-pointer  ">
          <React width={25} height={25} />
        </div>
      </Html>
      <Html
        scale={1}
        rotation={[0, 0, 0]}
        position={[6, 5, 0]}
        transform
        occlude
      >
        <div className="bg-[#303030] rounded-full p-2 cursor-pointer  ">
          <SpringBoot width={25} height={25} />
        </div>
      </Html>
      <Html
        scale={1}
        rotation={[0, 0, 0]}
        position={[-6, 4, 0]}
        transform
        occlude
      >
        <div className="bg-[#303030] rounded-full p-2 cursor-pointer  ">
          <Next width={25} height={25} fill={"#fff"} />
        </div>
      </Html>
      <Html
        scale={1}
        rotation={[0, 0, 0]}
        position={[5.3, 2.2, 0]}
        transform
        occlude
      >
        <div className="bg-[#303030] rounded-full p-2 cursor-pointer  ">
          <Postgres width={25} height={25} />
        </div>
      </Html>
      <Html
        scale={1}
        rotation={[0, 0, 0]}
        position={[-5.2, 1, 0]}
        transform
        occlude
      >
        <div className="bg-[#303030] rounded-full p-2 cursor-pointer  ">
          <Java width={25} height={25} />
        </div>
      </Html>
    </group>
  );
}

useGLTF.preload("/mac.glb");
